### ISSUE TITLE
Null feature only upon using SOS 2.0.0

### ISSUE THREAD

**Issue by meliezer** [52North/SensorWebClient#147]
Hello,
sensorwebclient-webapp-3.3.0-rc.3-SNAPSHOT working with SOS 4.1 at http://nodc.ogs.trieste.it/SOS4/sos ,using SOS 2.0.0.:
ERROR [DefaultQuartzScheduler_Worker-1] [ConfigurationContext.java:275] Error building server metadata
java.lang.NullPointerException: null
        at org.n52.shared.serializable.pojos.sos.Station.<init>(Station.java:62) ~[Station.class:na]
        at org.n52.server.da.oxf.DefaultMetadataHandler.performMetadataInterlinking(DefaultMetadataHandler.java:205) ~[DefaultMetadataHandler.class:na]
        at org.n52.server.da.oxf.DefaultMetadataHandler.performMetadataCompletion(DefaultMetadataHandler.java:118) ~[DefaultMetadataHandler.class:na]
        at org.n52.server.mgmt.ConfigurationContext.getSOSMetadata(ConfigurationContext.java:260) ~[ConfigurationContext.class:na]
        at org.n52.server.mgmt.SosMetadataUpdate.cacheMetadata(SosMetadataUpdate.java:153) [SosMetadataUpdate.class:na]
        at org.n52.server.mgmt.SosMetadataUpdate.updateService(SosMetadataUpdate.java:98) [SosMetadataUpdate.class:na]
        at org.n52.server.mgmt.SosMetadataUpdate.performServiceUpdateFor(SosMetadataUpdate.java:73) [SosMetadataUpdate.class:na]
        at org.n52.server.mgmt.SosMetadataUpdate.updateSosServices(SosMetadataUpdate.java:64) [SosMetadataUpdate.class:na]
        at org.n52.server.mgmt.schedule.CacheUpdateJob.execute(CacheUpdateJob.java:86) [CacheUpdateJob.class:na]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [JobRunShell.class:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [SimpleThreadPool$WorkerThread.class:na]

Based on debug messages I've added to the code, the null feature is of ID 'CTD_E2M3A_10597', but I do have a correct REST server response to http://nodc.ogs.trieste.it/SOS4/service/rest/features/CTD_E2M3A_10597
It happens also after a fresh deploy and clearing of Tomcat's cache.

Some details about debugging in DefaultMetadataHandler.java:
Once SOS 1.0.0. is defined instead of SOS 2.0.0.:

    feature, lookup.getFeature(featureId): correct and not null.
    lookup.getFeatures() is correct and not empty.
    metadata. getStations() is correct and not empty.

-- 
With kind regards,
Menashè

**Comment by ridoo** [comment]
@meliezer I gave a comment on your PR right here: https://github.com/meliezer/SensorWebClient/commit/7c702759c0b92fef023a57671ea4f71f850a85a8#commitcomment-9669224

Please check, if your capabilities document is consistent. Another note: The client is NOT consuming the REST API of the SOS. So don't expect the output of an interface which is not being confused to be available in another component (there may be other issues, workflows).
