### ISSUE TITLE
IllegalArgumentException: Illegal instant due to time zone offset transition

### ISSUE THREAD

**Issue by meliezer** [52North/SensorWebClient#150]
The above excpetion appears upon trying to move the time window of a time-series while working with shift dates.

You may want to consult http://joda-time.sourceforge.net/faq.html#illegalinstant

An example:
java.lang.IllegalArgumentException: Cannot parse "2014-03-30T02:05:20": Illegal instant due to time zone offset transition (Europe/Rome)
        at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:390) ~[DateTimeParserBucket.class:2.1]
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:849) ~[DateTimeFormatter.class:2.1]
        at org.joda.time.DateTime.parse(DateTime.java:144) ~[DateTime.class:2.1]
        at org.joda.time.DateTime.parse(DateTime.java:133) ~[DateTime.class:2.1]
        at org.n52.oxf.valueDomains.time.TimePosition.compareTo(TimePosition.java:552) ~[TimePosition.class:2.0.0-alpha.3.3]
        at org.n52.oxf.valueDomains.time.TimePosition.compareTo(TimePosition.java:48) ~[TimePosition.class:2.0.0-alpha.3.3]
        at java.util.ComparableTimSort.binarySort(ComparableTimSort.java:232) ~[na:1.7.0_65]
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:176) ~[na:1.7.0_65]
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:146) ~[na:1.7.0_65]
        at java.util.Arrays.sort(Arrays.java:472) ~[na:1.7.0_65]
        at org.n52.oxf.feature.sos.ObservationSeriesCollection.getSortedTimeArray(ObservationSeriesCollection.java:228) ~[ObservationSeriesCollection.class:2.0.0-alpha.3.3]
        at org.n52.server.io.Generator.updateTimeSeriesPropertiesForHavingData(Generator.java:159) ~[Generator.class:na]
        at org.n52.server.io.Generator.getFeatureCollectionFor(Generator.java:139) ~[Generator.class:na]
        at org.n52.server.io.EESGenerator.createChart(EESGenerator.java:107) ~[EESGenerator.class:na]
        at org.n52.server.io.EESGenerator.producePresentation(EESGenerator.java:85) ~[EESGenerator.class:na]
        at org.n52.server.service.EESDataServiceImpl.getEESOverview(EESDataServiceImpl.java:58) ~[EESDataServiceImpl.class:na]

**Comment by ridoo** [comment]
Well to find out where the problem lies, it would be helpful to have the GetObservationResponse at hand to see what times the SOS is responding. 

Anyway, I expect JodaTime tries to parse the time with the locally set (on your computer) timezone which is `Europe/Rome` as the timezone is completely missing. If so, the string `2014-03-30T02:05:20` would indeed be illegal. Probably you should configure your SOS instance to spit out time strings which are legal in any case

**Comment by meliezer** [comment]
You are right. Z should be appended as the timezone is UTC. I expect it will resolve the problem.
Thank you.

**Comment by meliezer** [comment]
Actually I do see "2014-03-30 02:05:20" in database, but it would be useless adding Z since the colum type is timestamp and not timestampz. I see no other place where sos keeps a timezone information. So, the bug exists and I have no way to resolve it.
In SOS admin the optional "Date format of GML" is empty.
I would like to add two questions:
1. Upon feeding sos with a date which lacks the timezone, will sos save it in db doing some timezone conversion or simply assume it's UTC?
2. If a non UTC timezone is specified, sos converts it to utc before saving in db?
3. The sos web client always show the date translated to the web client local time and as appears in db?
--
Menashè

**Comment by ridoo** [comment]
@meliezer it would be helpful if you could try to provide more context to your comments. For example, the implementation log is much too short to know where it has been logged (you don't say either) and in what context the message appears.

BTW: if you are talking about a SOS bug, or if you are unsure how SOS treats times and timezones please create an issue at https://github.com/52North/SOS/issues.

The Sensor Web Client translates the dates to the clients locale.

**Comment by meliezer** [comment]
Quoting from my first post: "The above excpetion appears upon trying to move the time window of a time-series while working with shift dates." I mean a shift to dayligth saving time. Just choose a time frame which includes the shift at 03-30. Here is a bigger log from 3.3.0-rc.3-SNAPSHOT:
2015-03-18 12:08:35,633 DEBUG [ajp-nio-8010-exec-115] [ObservationAccessor.java:94] Received 120 observations for CT_E2M3A@http://nodc.ogs.trieste.it/SOS4/sos
2015-03-18 12:08:35,665 DEBUG [ajp-nio-8010-exec-115] [TimeseriesFactory.java:77] Compressionlevel none
2015-03-18 12:08:35,667 DEBUG [ajp-nio-8010-exec-115] [TimeseriesFactory.java:120] Compressed observations from 120 to 120
2015-03-18 12:08:35,719 DEBUG [ajp-nio-8010-exec-115] [EESGenerator.java:98] Produced EES Overview diagram client/jfreechart/image?filename=jfreechart-onetime-6993232156425162619.png
2015-03-18 12:08:35,831 DEBUG [ajp-nio-8010-exec-119] [EESGenerator.java:95] Produced EES diagram client/jfreechart/image?filename=jfreechart-onetime-6792941721912716264.png
2015-03-18 12:08:35,831 DEBUG [ajp-nio-8010-exec-119] [EESGenerator.java:158] Reduce 0 Entities to 0 Tooltips
2015-03-18 12:08:37,230 DEBUG [ajp-nio-8010-exec-116] [EESDataServiceImpl.java:44] Performing EES diagram data request.
2015-03-18 12:08:37,232 DEBUG [ajp-nio-8010-exec-118] [EESDataServiceImpl.java:56] Performing EES overview data request
2015-03-18 12:08:37,319 DEBUG [ajp-nio-8010-exec-116] [ObservationAccessor.java:94] Received 24 observations for CT_E2M3A@http://nodc.ogs.trieste.it/SOS4/sos
2015-03-18 12:08:37,325 DEBUG [ajp-nio-8010-exec-116] [TimeseriesFactory.java:77] Compressionlevel none
2015-03-18 12:08:37,326 DEBUG [ajp-nio-8010-exec-116] [TimeseriesFactory.java:120] Compressed observations from 24 to 24
2015-03-18 12:08:37,408 DEBUG [ajp-nio-8010-exec-118] [ObservationAccessor.java:94] Received 120 observations for CT_E2M3A@http://nodc.ogs.trieste.it/SOS4/sos
2015-03-18 12:08:37,439 DEBUG [ajp-nio-8010-exec-118] [TimeseriesFactory.java:77] Compressionlevel none
2015-03-18 12:08:37,441 DEBUG [ajp-nio-8010-exec-118] [TimeseriesFactory.java:120] Compressed observations from 120 to 120
2015-03-18 12:08:37,484 DEBUG [ajp-nio-8010-exec-118] [EESGenerator.java:98] Produced EES Overview diagram client/jfreechart/image?filename=jfreechart-onetime-2403745721394565754.png
2015-03-18 12:08:37,578 DEBUG [ajp-nio-8010-exec-116] [EESGenerator.java:95] Produced EES diagram client/jfreechart/image?filename=jfreechart-onetime-3954780886199447025.png
2015-03-18 12:08:37,578 DEBUG [ajp-nio-8010-exec-116] [EESGenerator.java:158] Reduce 0 Entities to 0 Tooltips
2015-03-18 12:08:38,609 DEBUG [ajp-nio-8010-exec-115] [EESDataServiceImpl.java:44] Performing EES diagram data request.
2015-03-18 12:08:38,626 DEBUG [ajp-nio-8010-exec-119] [EESDataServiceImpl.java:56] Performing EES overview data request
2015-03-18 12:08:38,714 DEBUG [ajp-nio-8010-exec-115] [ObservationAccessor.java:94] Received 24 observations for CT_E2M3A@http://nodc.ogs.trieste.it/SOS4/sos
2015-03-18 12:08:38,719 DEBUG [ajp-nio-8010-exec-115] [TimeseriesFactory.java:77] Compressionlevel none
2015-03-18 12:08:38,720 DEBUG [ajp-nio-8010-exec-115] [TimeseriesFactory.java:120] Compressed observations from 24 to 24
2015-03-18 12:08:38,787 DEBUG [ajp-nio-8010-exec-119] [ObservationAccessor.java:94] Received 119 observations for CT_E2M3A@http://nodc.ogs.trieste.it/SOS4/sos
2015-03-18 12:08:38,831 ERROR [ajp-nio-8010-exec-119] [EESDataServiceImpl.java:60] Exception occured on server side.
java.lang.IllegalArgumentException: Cannot parse "2014-03-30T02:05:20": Illegal instant due to time zone offset transition (Europe/Rome)
        at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:390) ~[DateTimeParserBucket.class:2.1]
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:849) ~[DateTimeFormatter.class:2.1]
        at org.joda.time.DateTime.parse(DateTime.java:144) ~[DateTime.class:2.1]
        at org.joda.time.DateTime.parse(DateTime.java:133) ~[DateTime.class:2.1]
        at org.n52.oxf.valueDomains.time.TimePosition.compareTo(TimePosition.java:552) ~[TimePosition.class:2.0.0-alpha.3.3]
        at org.n52.oxf.valueDomains.time.TimePosition.compareTo(TimePosition.java:48) ~[TimePosition.class:2.0.0-alpha.3.3]
        at java.util.ComparableTimSort.binarySort(ComparableTimSort.java:258) ~[na:1.8.0_40]
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:203) ~[na:1.8.0_40]
        at java.util.Arrays.sort(Arrays.java:1246) ~[na:1.8.0_40]
        at org.n52.oxf.feature.sos.ObservationSeriesCollection.getSortedTimeArray(ObservationSeriesCollection.java:228) ~[ObservationSeriesCollection.class:2.0.0-alpha.3.3]
        at org.n52.server.io.Generator.updateTimeSeriesPropertiesForHavingData(Generator.java:159) ~[Generator.class:na]
        at org.n52.server.io.Generator.getFeatureCollectionFor(Generator.java:139) ~[Generator.class:na]
        at org.n52.server.io.EESGenerator.createChart(EESGenerator.java:107) ~[EESGenerator.class:na]
        at org.n52.server.io.EESGenerator.producePresentation(EESGenerator.java:85) ~[EESGenerator.class:na]
        at org.n52.server.service.EESDataServiceImpl.getEESOverview(EESDataServiceImpl.java:58) ~[EESDataServiceImpl.class:na]
        at org.n52.server.service.rpc.RpcEESDataServlet.getEESOverview(RpcEESDataServlet.java:64) [RpcEESDataServlet.class:na]
        at sun.reflect.GeneratedMethodAccessor1608.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561) [RPC.class:na]
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265) [RemoteServiceServlet.class:na]
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305) [RemoteServiceServlet.class:na]
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62) [AbstractRemoteServiceServlet.class:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api-3.1.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api-3.1.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat8-websocket-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:168) [CORSFilter.class:1.8]
        at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:233) [CORSFilter.class:1.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat8-util-8.0.14.jar:8.0.14]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
2015-03-18 12:08:39,005 DEBUG [ajp-nio-8010-exec-115] [EESGenerator.java:95] Produced EES diagram client/jfreechart/image?filename=jfreechart-onetime-4076711638361825339.png

**Comment by ridoo** [comment]
@meliezer your postings are very hard to read ... I would really appreciate if you could spend more time in organizing your comments. Always a hassle to go through ... also recommended reading (applies also to GitHub issues):

  http://52north.org/resources/mailing-lists-and-forums/guidelines

Anyway, I see that you are using a Client version which uses an older OX-Framework version. There has been made a fix (https://github.com/52North/OX-Framework/commit/2e771813ad4e61ffb2325e1f060509ae647f2b98) regarding to time handling there. Please either use the newest client from the `develop` branch or just [change the version](https://github.com/52North/SensorWebClient/blob/master/pom.xml#L1008) if you're on `master` branch

**Comment by meliezer** [comment]
I'll do my best.

Thanks for your recommendation. However, it changes nothing:
java.lang.IllegalArgumentException: Cannot parse "2014-03-30T02:05:20": Illegal instant due to time zone offset transition (Europe/Rome)
        at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:390) ~[DateTimeParserBucket.class:2.1]
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:849) ~[DateTimeFormatter.class:2.1]
        at org.joda.time.DateTime.parse(DateTime.java:144) ~[DateTime.class:2.1]
        at org.joda.time.DateTime.parse(DateTime.java:133) ~[DateTime.class:2.1]
        at org.n52.oxf.valueDomains.time.TimePosition.compareTo(TimePosition.java:552) ~[TimePosition.class:2.0.0-alpha.3.4-SNAPSHOT]
        at org.n52.oxf.valueDomains.time.TimePosition.compareTo(TimePosition.java:48) ~[TimePosition.class:2.0.0-alpha.3.4-SNAPSHOT]

**Comment by ridoo** [comment]
Had a deeper look at the OX-F code ... seems I could reproduce it (see https://github.com/52North/OX-Framework/issues/38).

I will check, when I can fix that issue.
