### ISSUE TITLE
org.n52.oxf.OXFException: Could not parse response to XML

### ISSUE THREAD

**Issue by meliezer** [52North/SensorWebClient#152]
It's not easy reproducing it, but it seems that sometimes there is an attempt to read the xml reply before it's ready.

```
[EESDataServiceImpl.java:56] Performing EES overview data request
..
Caused by: org.n52.server.da.AccessException: Could not execute GetObservation request.
        at org.n52.server.da.oxf.ObservationAccessor.sendRequest(ObservationAccessor.java:141) ~[ObservationAccessor.class:na]
..
Caused by: org.n52.oxf.OXFException: Could not parse response to XML.
        at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:302) ~[SOSAdapter.class:2.0.0-alpha.3.3]
        at org.n52.server.da.oxf.SOSAdapter_OXFExtension.doOperation(SOSAdapter_OXFExtension.java:86) ~[SOSAdapter_OXFExtension.class:na]
        at org.n52.server.da.oxf.OperationAccessor.call(OperationAccessor.java:55) ~[OperationAccessor.class:na]
        at org.n52.server.da.oxf.OperationAccessor.call(OperationAccessor.java:39) ~[OperationAccessor.class:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
        ... 1 common frames omitted
Caused by: org.apache.xmlbeans.XmlException: error: Unexpected end of file after null
        at org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3511) ~[Locale$SaxLoader.class:na]
        at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1277) ~[Locale.class:na]
        at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1264) ~[Locale.class:na]
        at org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:345) ~[SchemaTypeLoaderBase.class:na]
        at org.apache.xmlbeans.XmlObject$Factory.parse(XmlObject.java:688) ~[XmlObject$Factory.class:2.6.0-r1364789]
        at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:296) ~[SOSAdapter.class:2.0.0-alpha.3.3]
        ... 7 common frames omitted
Caused by: org.xml.sax.SAXParseException: Unexpected end of file after null
        at org.apache.xmlbeans.impl.piccolo.xml.Piccolo.reportFatalError(Piccolo.java:1038) ~[Piccolo.class:na]
        at org.apache.xmlbeans.impl.piccolo.xml.Piccolo.parse(Piccolo.java:723) ~[Piccolo.class:na]
        at org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3479) ~[Locale$SaxLoader.class:na]
```

**Comment by ridoo** [comment]
yeah ... I know this error and also solved such error by wrapping XMLbeans streams with `AutoCloseInputStream` you proposed. 

Perhaps I missed that location ... I'll check! Anyway, this issue relates to the https://github.com/52North/OX-Framework AFAICS ...
