### ISSUE TITLE
Corrupted cache

### ISSUE THREAD

**Issue by meliezer** [52North/SensorWebClient#154]
Hello,
sensorwebclient-webapp-3.3.0-rc.3-SNAPSHOT working with SOS 4.1 at http://nodc.ogs.trieste.it/SOS4/sos , using SOS 2.0.0.: 
The client fails creating a non-corrupted cache. The corrupted file has only few bytes.
Debian 8, Tomcat 8, Java: Oracle 1.8.0_20-b26 
Log:
2015-02-26 17:38:29,595 INFO [DefaultQuartzScheduler_Worker-1] [SosMetadataUpdate.java:76] Update service metadata for 'http://nodc.ogs.trieste.it/SOS4/sos'
2015-02-26 17:38:29,602 ERROR [DefaultQuartzScheduler_Worker-1] [ConfigurationContext.java:361] Could not load SOS from null
java.lang.NullPointerException: null
    at org.n52.server.mgmt.ConfigurationContext.addNewSOSMetadata(ConfigurationContext.java:355) ~[ConfigurationContext.class:na]
    at org.n52.server.mgmt.SosMetadataUpdate.loadMetadataFromCache(SosMetadataUpdate.java:120) [SosMetadataUpdate.class:na]
    at org.n52.server.mgmt.SosMetadataUpdate.updateService(SosMetadataUpdate.java:80) [SosMetadataUpdate.class:na]
    at org.n52.server.mgmt.SosMetadataUpdate.performServiceUpdateFor(SosMetadataUpdate.java:63) [SosMetadataUpdate.class:na]
    at org.n52.server.mgmt.SosMetadataUpdate.updateSosServices(SosMetadataUpdate.java:55) [SosMetadataUpdate.class:na]
    at org.n52.server.mgmt.schedule.CacheUpdateJob.execute(CacheUpdateJob.java:86) [CacheUpdateJob.class:na]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [JobRunShell.class:na]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [SimpleThreadPool$WorkerThread.class:na]
2015-02-26 17:38:29,603 INFO [DefaultQuartzScheduler_Worker-1] [SosMetadataUpdate.java:57] Cache update took 0.009 seconds.
2015-02-26 17:38:29,603 INFO [DefaultQuartzScheduler_Worker-1] [CacheUpdateJob.java:93] Update process complete. 

--
With kind regards, 
Menashè

**Comment by ridoo** [comment]
Fixed with commit @2ee94fd

**Comment by meliezer** [comment]
Thanks, it works!
