### ISSUE TITLE
Could not get OperationResult from SOS 4.2.0

### ISSUE THREAD

**Issue by meliezer** [52North/SensorWebClient#155]
Hello,
sensorwebclient-webapp-3.3.0-rc.3-SNAPSHOT working with SOS 4.2.0 (Master branch) at http://nodc.ogs.trieste.it/SOS42/sos , using SOS 2.0.0.: 
I see no sensors.

Log:
```
Request -> getPhenomenons(sosUrl: http://nodc.ogs.trieste.it/SOS42/sos, filter: QueryParameters [service: null, station: null, offering: null, procedure: null, phenomenon: null, feature: null, spatialFilter: null, offset: 0, size: 0])
2015-03-27 13:57:48,495 DEBUG [http-nio-8082-exec-3] [DefaultMetadataHandler.java:161] Going to send #1 DescribeSensor requests.
2015-03-27 13:57:48,576 WARN [http-nio-8082-exec-3] [DefaultMetadataHandler.java:234] Could NOT get OperationResult from SOS for 'urn:ogc:object:feature:Sensor:OGS:pH_P0007_E2M3A'.
org.n52.oxf.OXFException: Could not parse response to XML.
        at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:302) ~[SOSAdapter.class:2.0.0-alpha.3.4-SNAPSHOT]
        at org.n52.server.da.oxf.SOSAdapter_OXFExtension.doOperation(SOSAdapter_OXFExtension.java:86) ~[SOSAdapter_OXFExtension.class:na]
        at org.n52.server.da.oxf.OperationAccessor.call(OperationAccessor.java:55) ~[OperationAccessor.class:na]
        at org.n52.server.da.oxf.OperationAccessor.call(OperationAccessor.java:39) ~[OperationAccessor.class:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_75]
Caused by: org.apache.xmlbeans.XmlException: error: Unexpected end of file after null
        at org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3511) ~[Locale$SaxLoader.class:na]
        at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1277) ~[Locale.class:na]
        at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1264) ~[Locale.class:na]
        at org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:345) ~[SchemaTypeLoaderBase.class:na]
        at org.apache.xmlbeans.XmlObject$Factory.parse(XmlObject.java:688) ~[XmlObject$Factory.class:2.6.0-r1364789]
        at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:296) ~[SOSAdapter.class:2.0.0-alpha.3.4-SNAPSHOT]
        ... 7 common frames omitted

```

Debian 8, Tomcat 8, Java: Oracle 1.8.0_20-b26
Sensor Web Client Web Application, Git-Branch 'develop' with state '5c028fde20a45f6022e1d21ce5510cd57a2afd62 

--
Menashè

**Comment by ridoo** [comment]
Probably the same as #152

**Comment by meliezer** [comment]
Thank you for this fix which resolves the problem.
